package model

const (
	CLIENT_STATUS_FREE = iota + 1
	CLIENT_STATUS_BUSY
	CLIENT_STATUS_OFFLINE
)

const (
	TASK_STATUS_CREATED = iota + 1
	TASK_STATUS_RUNNING
	TASK_STATUS_FINISHED
	TASK_STATUS_FAILED
)

const (
	TASK_TYPE_PING       = "ping"
	TASK_TYPE_IPERF      = "iperf"
	TASK_TYPE_TRACEROUTE = "traceroute"
)
