FROM golang:1.20 as builder

ENV GO111MODULE=on

WORKDIR /app

COPY . .

RUN go build -o client.bin ./client/main.go

RUN mkdir output && cp client.bin output/ && cp -r client/etc output/

FROM ubuntu:latest

WORKDIR /app

COPY --from=builder /app/output .

RUN apt-get update && apt-get install -y iperf traceroute && mkdir /app/logs

CMD ["/app/client.bin", "-f", "/app/etc/config.yaml"]