apiVersion: v1
kind: Pod
metadata:
  name: cs5296-client-pod-node-1-1
  namespace: default
spec:
  containers:
    - name: cs5296-client
      image: ahussp/cs5296-client
      ports:
        - containerPort: 3000
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SERVER_ADDR
          value: "http://cs5296-server-service.default.svc.cluster.local"
  nodeSelector:
    kubernetes.io/hostname: k8s-node-1

---
apiVersion: v1
kind: Pod
metadata:
  name: cs5296-client-pod-node-1-2
  namespace: default
spec:
  containers:
    - name: cs5296-client
      image: ahussp/cs5296-client
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SERVER_ADDR
          value: "http://cs5296-server-service.default.svc.cluster.local"
  nodeSelector:
    kubernetes.io/hostname: k8s-node-1

---
apiVersion: v1
kind: Pod
metadata:
  name: cs5296-client-pod-node-2-1
  namespace: default
spec:
  containers:
    - name: cs5296-client
      image: ahussp/cs5296-client
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SERVER_ADDR
          value: "http://cs5296-server-service.default.svc.cluster.local"
  nodeSelector:
    kubernetes.io/hostname: k8s-node-2