DebugMode: false
AppName: cs5296-project-server
ListenOn: 0.0.0.0:8080
MySQL: "root:123456@tcp(host.docker.internal:3306)/cs5269_project?charset=utf8mb4&parseTime=True&loc=Local"
LogPath: /app/logs
ClientOfflineThreshold: 10